version: '{build}'
image: Visual Studio 2017

install:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

branches:
  only:
  - master

clone_depth: 1

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: .\build.ps1 -Target Default -Verbosity Diagnostic

test: off

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\artifacts\**\*.xml
  name: xUnit Test Results

cache:
- tools -> build.cake
- packages -> build.cake
